# Trigger of the pipeline
on:
  # initiate the pipeline when there is a push event in the main branch
  push:
    branches:
      - main

jobs:
  # Stage 1: Building the docker image
  build-docker-image:
    name: The job to build the application docker image
    # To define the machine that runs a job we use "runs-on"
    runs-on: csd-windows-local  # Using the self-hosted runner
    # The instructions are defined as steps
    steps:
      - name: Clone and Checkout to the repository
        uses: actions/checkout@v2  # this is a GitHub action (pre-defined job)
                                   # that clones the project into the working directory

      - name: Build Docker Image
        run: docker build -t flask-app-1:v1.0.0 -f Dockerfile .

  test:
    name: Unit testing of the application
    needs: [build-docker-image]
    runs-on: csd-windows-local
    steps:
      - name: Clone and Checkout to the repository
        uses: actions/checkout@v2  # this is a GitHub action (pre-defined job)
        # that clones the project into the working directory

      - name: Set up a virtual environment
        run: |
          python -m venv venv  # Create a virtual environment in a directory called venv
          venv/Scripts/activate  # Activate the virtual environment
          pip install flask
          pip install pytest

      - name: Run unit tests inside the virtual environment
        run: |
          venv/Scripts/activate  # Activate the virtual environment
          pytest tests/  # Runs the unit testing files under the directory tests

  deploy-docker-image:
    name: Deploy the flask image
    needs: [build-docker-image, test]
    runs-on: csd-windows-local  # Using the self-hosted runner
    steps:
      - name: Deploy the image
        run: docker run -d -p 5000:5000 flask-app-1:v1.0.0  # -d tag allows us to run the container in the background
